version: '3.7'

# Define services
services:
  # App backend service
  # app-server:
  #   # Configuration for building the docker image for the backend service
  #   build:
  #     dockerfile: ./Dockerfile
  #   ports:
  #     - "8080:8080" # Forward the exposed port 8080 on the container to port 8080 on the host machine
  #   restart: always
  #   depends_on:
  #     - db # This service depends on mysql. Start that first.
  #   environment:
  #     # Pass environment variables to the service
  #     SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/testingonline?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
  #     SPRING_DATASOURCE_USERNAME: testingonline
  #     SPRING_DATASOURCE_PASSWORD: testingonline
  #   networks:
  #     # Networks to join (Services on the same network can communicate with each other using their name)
  #     - testingonline

  # Database Service (PostgresSQL)
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: testingonline
      MYSQL_USER: testingonline
      MYSQL_PASSWORD: testingonline
      MYSQL_ROOT_PASSWORD: "123456"
    volumes:
      - ./data/mysql:/var/lib/mysql

  book:
    restart: always
    build: ./
    image: nguyenddthong/book:v1.0
    ports:
      - "8080:8080"
    depends_on:
      - db
    volumes:
      - ./application.properties:/application.properties
    environment:
      - TZ=Asia/Ho_Chi_Minh

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888

  kafka:
    image: confluentinc/cp-kafka:latest
    ports:
      - 9092:9092
    container_name: kafka
    links:
      - zookeeper
    environment:
      ZOOKEEPER_CONNECT: zookeeper:2181
      BROKER_ID: 1
      LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      INTER_BROKER_LISTENER_NAME: PLAINTEXT
      ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9092